### ISSUE TITLE
Rise of the Empire 

### ISSUE THREAD

**Issue by FanaticBass606** [NMSCD/Community-Search#7]
Helping others and each other

**Comment by Khaoz-Topsy** [comment]
Hi @FanaticBass606 
Your submission has been added! 🎉
It is visible in the Assistant for No Man's Sky apps as well as on our website ([community.nmscd.com](https://community.nmscd.com))

I noticed that you selected the Discord tag but did not include a Discord link. Feel free to reopen this issue with the Discord link and I will add it to your community link
